# .github/workflows/check-updates.yml
name: Check Driver Policy Updates

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  check-updates:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 tqdm
        shell: powershell

      - name: Initialize latest.txt if not exists
        run: |
          if (-not (Test-Path latest.txt)) {
            "" | Out-File -FilePath latest.txt
          }
        shell: powershell

      - name: Check for updates
        id: check
        run: python check_update.py
        shell: powershell

      - name: Trigger update workflow if needed
        if: steps.check.outputs.update_needed == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Process Driver Policy Update"
          repo: nechyo/windows-driver-blocklists
          inputs: |
            {
              "update_name": "${{ steps.check.outputs.update_name }}"
            }
