# .github/workflows/check-updates.yml
name: Check Driver Policy Updates

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-and-update:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 tqdm
        shell: powershell

      - name: Initialize latest.txt if not exists
        run: |
          if (-not (Test-Path latest.txt)) {
            "" | Out-File -FilePath latest.txt
          }
        shell: powershell

      - name: Check for updates and get update name
        id: check
        run: python check_update.py
        shell: powershell

      - name: Download and extract policy
        if: steps.check.outputs.update_needed == 'true'
        run: |
          # Install scoop and 7-Zip
          (New-Object System.Net.WebClient).DownloadFile('https://get.scoop.sh', 'scoop.ps1')
          ./scoop.ps1 -RunAsAdmin
          scoop install 7zip
          
          python downloader.py

          ./process-esd.ps1
        shell: powershell

      - name: Upload Driver Policy Update - ${{ steps.check.outputs.update_name }}
        if: steps.check.outputs.update_needed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.check.outputs.update_name }}
          path: output/driversipolicy.p7b
          retention-days: 90
          if-no-files-found: error

      - name: Update latest UUID
        if: steps.check.outputs.update_needed == 'true'
        run: |
          Copy-Item current_uuid.txt latest.txt
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add latest.txt
          git commit -m "${{ steps.check.outputs.update_name }}"
          git push
        shell: powershell