# .github/workflows/process-update.yml
name: Process Driver Policy Update

on:
  workflow_dispatch:
    inputs:
      update_name:
        required: true
        type: string
        description: 'Update name to process'
      current_uuid:
        required: true
        type: string
        description: 'Current uuid to process'

permissions:
  contents: write

jobs:
  process-update:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 tqdm
        shell: powershell

      - name: Download and extract policy
        run: |
          (New-Object System.Net.WebClient).DownloadFile('https://get.scoop.sh', 'scoop.ps1')
          ./scoop.ps1 -RunAsAdmin
          scoop install 7zip
          
          python check_update.py
          python downloader.py
          ./process-esd.ps1
          ./process-p7b.ps1
        shell: powershell

      - name: Create and push tag
        id: create_tag
        run: |
          TAG_NAME="driver-update-${{ inputs.current_uuid }}"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Upload Driver Policy Update
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.update_name }}
          path: |
            output/driversipolicy.p7b
            blacklists/driversipolicy.xml
          retention-days: 90
          if-no-files-found: error

      - name: Upload Driver Policy to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          release_name: ${{ inputs.update_name }}
          file_glob: true
          file: "*/driversipolicy.{p7b,xml}"
          body: |
            Driver Policy Update: ${{ inputs.update_name }}-${{ inputs.current_uuid }}

            This release includes an updated driver blocklist policy file:
            - Filename: driversipolicy.p7b and driversipolicy.xml
            - Purpose: Enhanced security and compatibility.
            
            Please download the file and use it in your environment as necessary.

      - name: Update latest UUID
        run: |
          Copy-Item current_uuid.txt latest.txt
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add latest.txt
          git commit -m "${{ inputs.update_name }}"
          git push
        shell: powershell
